# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'oc-string' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'RegexKitLite', '~> 4.0'
  # pod 'YYKit', '~> 1.0.9'
  # Pods for oc-string

  target 'oc-stringTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
